# -*- coding: utf-8 -*-
"""Problem-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnHe4v6HRpneGMi9pzpGeixU8QPdUfvX
"""

import heapq

def viraj_merge_sorted_arrays(arrays):
    merged = []
    heap = [(array[0], i, 0) for i, array in enumerate(arrays) if array]
    heapq.heapify(heap)

    while heap:
        val, array_index, element_index = heapq.heappop(heap)
        merged.append(val)
        if element_index + 1 < len(arrays[array_index]):
            next_val = arrays[array_index][element_index + 1]
            heapq.heappush(heap, (next_val, array_index, element_index + 1))

    return merged

# Test cases
array1 = [1, 3, 5, 7]
array2 = [2, 4, 6, 8]
array3 = [0, 9, 10, 11]

print("Input:")
print("array1 =", array1)
print("array2 =", array2)
print("array3 =", array3)

output = viraj_merge_sorted_arrays([array1, array2, array3])
print("\nOutput:")
print(output)