# -*- coding: utf-8 -*-
"""Problem-0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hds861C_wadjWxI3z001M1PtNHYtSNhl
"""

def fib(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return fib(n-1) + fib(n-2)

x=fib(5)
print(x)